### ISSUE TITLE
How to write to an Archive you've created and then opened?

### ISSUE THREAD

**Issue by chrisekelley** [RangerMauve/dat-archive-web#2]
I made a [simple example](https://github.com/chrisekelley/dat-archive-web-test/blob/master/index.js#L59) that tests creating a new Archive, writes to it, then opens it with DatArchive(url), and tries to write to it again. I get the following error:

```
dat-archive-web.js:2501 Uncaught (in promise) ArchiveNotWritableError: Cannot write to this archive ; Not the owner
    at assertWritePermission (http://127.0.0.1:8080/assets/dat-archive-web.js:322:11)
    at timer (http://127.0.0.1:8080/assets/dat-archive-web.js:193:13)
```

If this because the archive does not have access to the private keys that were generated when it was created? I see that hyperdrive has a 'writable' property in the metadata that must be set. Or is this an operation that needs to happen on the filesystem/node side inside dat-gateway?

**Comment by RangerMauve** [comment]
I think the problem is that you're using the default storage which is `random-access-memory` which means each time you create an archive it's loading all its data for the first time. Instead you should use `random-access-idb` in the browser. You'll need to create a custom Manager that does this. Check out my [demo code](https://github.com/RangerMauve/dat-archive-web/blob/gh-pages/demo.js) for how that works.

**Comment by chrisekelley** [comment]
Thanks a lot - your demo code was very helpful; I got it working and updated my simple example.
